//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YAMBOLY.PORTALADMINISTRADOR.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public int ErrorLogId { get; set; }
        public string internalException { get; set; }
        public string errorMessage { get; set; }
        public string browser { get; set; }
        public string stackTrace { get; set; }
        public string errorType { get; set; }
        public string sessionKeys { get; set; }
        public string errorTimeStamp { get; set; }
    }
}
