//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YAMBOLY.PORTALADMINISTRADOR.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolesViews
    {
        public int RolViewId { get; set; }
        public int RolId { get; set; }
        public int ViewId { get; set; }
        public Nullable<bool> RolesViewsState { get; set; }
    
        public virtual Roles Roles { get; set; }
        public virtual Views Views { get; set; }
    }
}
