//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YAMBOLY.PORTALADMINISTRADOR.MODEL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YAMBOLY_PORTALADMINISTRADOREntities : DbContext
    {
        public YAMBOLY_PORTALADMINISTRADOREntities()
            : base("name=YAMBOLY_PORTALADMINISTRADOREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ErrorLog> ErrorLog { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<RolesViews> RolesViews { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<ViewGroup> ViewGroup { get; set; }
        public virtual DbSet<Views> Views { get; set; }
    }
}
